 SELECT
      v.id AS verse_id,
      v.reference,
      v.book,
      v.chapter,
      v.verse,
      v.hebrew_text,
      v.english_text,
      v.figurative_detection_deliberation,
      v.instances_detected,
      fl.id AS figurative_id,
      fl.figurative_text,
      fl.figurative_text_in_hebrew,
      fl.explanation,
      fl.confidence,
      fl.metaphor,
      fl.simile,
      fl.personification,
      fl.idiom,
      fl.hyperbole,
      fl.metonymy,
      fl.other,
      fl.final_metaphor,
      fl.final_simile,
      fl.final_personification,
      fl.final_figurative_language,
      fl.validation_decision_metaphor,
      fl.validation_decision_simile,
	  fl.validation_decision_metonymy,
	  fl.validation_reason_metaphor,
	  fl.validation_reason_simile,
	  fl.validation_reason_metonymy,
	  target,
	  vehicle,
	  ground,
	  posture
  FROM verses v
    LEFT JOIN figurative_language fl ON v.id = fl.verse_id
  ORDER BY v.book, v.chapter, v.verse, fl.id